name:                personal-site
version:             0.1.0.0
github:              "jacobprudhomme/personal-site"
license:             BSD3
author:              "Jacob Prud'homme"
maintainer:          "jacob.pkmn@gmail.com"
copyright:           "2020 Jacob Prud'homme"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            My personal website, built with Slick
category:            Slick-Site

description:         The configuration for Slick, the SSG that builds my personal website

executables:
  build-site:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base >= 4.7 && < 5
    - shake
    - slick
    - text
    - containers
    - unordered-containers
    - lens
    - aeson
    - lens-aeson
    - time
    - clay
