name: Build and deploy to GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      GHC_VERSION: '8.6.5'
      CABAL_VERSION: '3.0'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: ${{ env.GHC_VERSION }}
          cabal-version: ${{ env.CABAL_VERSION }}

      - name: Cache cabal store
        uses: actions/cache@v2
        with:
          path: ~/.cabal/store
          key: cabal-store-${{ runner.OS }}-${{ env.GHC_VERSION }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            cabal-store-${{ runner.OS }}-${{ env.GHC_VERSION }}-
            cabal-store-${{ runner.OS }}-
      - run: cabal update
      - run: cabal build --only-dependencies
      - run: cabal build
      - run: cabal exec build-site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: master
          publish_dir: ./docs
          external_repository: jacobprudhomme/jacobprudhomme.github.io
